# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6b08b4b764c4ccaca1f1f13bb62584752e5882a1eaf2001c495b31a068bf5023c587c1fbf8b51c2b389b454716886c0b3dd1ef5229964d61c9c5ea44307501a

test:
  secret_key_base: 8c8e6462666178d78b913967fe417e02d29933504346245adccb75a3f313945c73cf0503380e722c96d743d955201c9b95954dcf0b7b72f5bc1e5dfdd312bea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
